version: '3.4'
services:
  wordpress:
    image: wordpress:latest
    volumes:
      - /nfs/wordpress:/var/www/html
    environment:
      TZ: America/Fortaleza
      WORDPRESS_DB_HOST: wordpress.cktoypu3k0fs.us-east-1.rds.amazonaws.com
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    ports:
      - 80:80
networks:
  wordpress-network:
    driver: bridge
