version: '3.4'
services:
  db:
    image: mysql:8.0.33
    command: --default_authentication_plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Fortaleza  # Fuso hor치rio de Fortaleza
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_USER: wordpress  # Nome de usu치rio principal
      MYSQL_PASSWORD: wordpress  # Senha principal
      MYSQL_DATABASE: wordpress
    ports:
      - "3306:3306"
    networks:
      - wordpress-network
    volumes:
      - /mnt/nfs/mysql_data:/var/lib/mysql
  wordpress:
    image: wordpress:latest
    restart: always
    environment:
      TZ: America/Fortaleza  # Fuso hor치rio de Fortaleza
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress  # Nome de usu치rio principal
      WORDPRESS_DB_PASSWORD: wordpress  # Senha principal
    ports:
      - 80:80
    volumes:
      - /nfs/wordpress:/var/www/html
    depends_on:
      - db 
    networks:
      - wordpress-network
networks:
  wordpress-network:
    driver: bridge
